version: '3.9'
services:

  balancer:
    image: openresty/openresty
    container_name: balancer
    hostname: balancer
    ports:
      - '8080:80'
    volumes:
      - ${PWD}/src/main/resources/nginx.conf:/etc/openresty/nginx.conf:ro
    #      - ${PWD}/src/main/resources/nginx.conf:/opt/bitnami/openresty/nginx/conf/nginx.conf:ro
    networks:
      my-network:
        ipv4_address: 172.22.0.2

  app01:
    build:
      context: ./
      dockerfile: Dockerfile.db01
    container_name: app01
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.12
  app02:
    build:
      context: ./
      dockerfile: Dockerfile.db01
    container_name: app02
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.13
  app03:
    build:
      context: ./
      dockerfile: Dockerfile.db02
    container_name: app03
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.16
  app04:
    build:
      context: ./
      dockerfile: Dockerfile.db02
    container_name: app04
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.17

  app05:
    build:
      context: ./
      dockerfile: Dockerfile.db03
    container_name: app05
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.14
  app06:
    build:
      context: ./
      dockerfile: Dockerfile.db03
    container_name: app06
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.15

  app07:
    build:
      context: ./
      dockerfile: Dockerfile.db04
    container_name: app07
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.18
  app08:
    build:
      context: ./
      dockerfile: Dockerfile.db04
    container_name: app08
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.19

  db01:
    image: mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--enforce-gtid-consistency=ON",
      "--gtid-mode=ON",
      "--server-id=1"
    ]
    container_name: db01
    hostname: db01
    environment:
      MYSQL_DATABASE: 'shard'
      MYSQL_USER: 'shard'
      MYSQL_PASSWORD: 'shard'
      MYSQL_ROOT_PASSWORD: 'mypass'
    networks:
      my-network:
        ipv4_address: 172.22.0.91
  db02:
    image: mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--enforce-gtid-consistency=ON",
      "--gtid-mode=ON",
      "--server-id=1"
    ]
    container_name: db02
    hostname: db02
    environment:
      MYSQL_DATABASE: 'shard'
      MYSQL_USER: 'shard'
      MYSQL_PASSWORD: 'shard'
      MYSQL_ROOT_PASSWORD: 'mypass'
    networks:
      my-network:
        ipv4_address: 172.22.0.92
  db03:
    image: mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--enforce-gtid-consistency=ON",
      "--gtid-mode=ON",
      "--server-id=2"
    ]
    container_name: db03
    hostname: db03
    environment:
      MYSQL_ROOT_PASSWORD: 'mypass'
    networks:
      my-network:
        ipv4_address: 172.22.0.93
  db04:
    image: mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--enforce-gtid-consistency=ON",
      "--gtid-mode=ON",
      "--server-id=2"
    ]
    container_name: db04
    hostname: db04
    environment:
      MYSQL_ROOT_PASSWORD: 'mypass'
    networks:
      my-network:
        ipv4_address: 172.22.0.94

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
