version: '3.9'
services:

  app01:
    build:
      context: ./
      dockerfile: Dockerfile.db01
    container_name: app01
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.12
  app02:
    build:
      context: ./
      dockerfile: Dockerfile.db01
    container_name: app02
    restart: on-failure
    networks:
      my-network:
        ipv4_address: 172.22.0.13

  db02:
    image: postgres
    container_name: db02
    hostname: db02
    environment:
      POSTGRES_DB: 'shard'
      POSTGRES_USER: 'shard'
      POSTGRES_PASSWORD: 'shard'
    networks:
      my-network:
        ipv4_address: 172.22.0.92

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
