FROM postgres:latest
#docker run --name my -e POSTGRES_USER=shard -e POSTGRES_PASSWORD=shard -e POSTGRES_DB=shard -d dimarudik/postgres
#docker build . -t dimarudik/postgres
RUN apt-get update -y && apt-get -y install curl vim less bsdmainutils binutils git git-lfs
