apiVersion: v1
kind: Service
metadata:
  name: shard02-db-service
spec:
  selector:
    app: shard02-db
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard02-db
spec:
  selector:
    matchLabels:
      app: shard02-db
  template:
    metadata:
      labels:
        app: shard02-db
    spec:
      containers:
        - name: shard02-db
          image: postgres:latest
          args: ["-c", "wal_level=logical"]
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name  : shard-configmap
                  key   : database_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name  : shard-secret
                  key   : username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name  : shard-secret
                  key   : password
